// <auto-generated />
using System;
using MesWorklog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesWorklog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808124705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MesWorklog.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_equipments");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lines");

                    b.ToTable("lines", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.LineProcess", b =>
                {
                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("line_id");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.HasKey("LineId", "ProcessId")
                        .HasName("pk_line_processes");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_line_processes_process_id");

                    b.ToTable("line_processes", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.PauseReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pause_reasons");

                    b.ToTable("pause_reasons", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_processes");

                    b.ToTable("processes", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualQty")
                        .HasColumnType("int")
                        .HasColumnName("actual_qty");

                    b.Property<int?>("ElapsedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("elapsed_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<int?>("NetOperatingMinutes")
                        .HasColumnType("int")
                        .HasColumnName("net_operating_minutes");

                    b.Property<int?>("OperatingMinutes")
                        .HasColumnType("int")
                        .HasColumnName("operating_minutes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_work_logs");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_work_logs_start_time");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_work_logs_work_order_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_work_logs_worker_id");

                    b.ToTable("work_logs", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLogPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PauseReasonId")
                        .HasColumnType("int")
                        .HasColumnName("pause_reason_id");

                    b.Property<DateTime>("PausedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paused_at");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resumed_at");

                    b.Property<int>("WorkLogId")
                        .HasColumnType("int")
                        .HasColumnName("work_log_id");

                    b.HasKey("Id")
                        .HasName("pk_work_log_pauses");

                    b.HasIndex("PauseReasonId")
                        .HasDatabaseName("ix_work_log_pauses_pause_reason_id");

                    b.HasIndex("WorkLogId")
                        .HasDatabaseName("ix_work_log_pauses_work_log_id");

                    b.ToTable("work_log_pauses", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("line_id");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int")
                        .HasColumnName("target_qty");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_work_orders_equipment_id");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_work_orders_line_id");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_work_orders_process_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workers");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.WorkerProcess", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.HasKey("WorkerId", "ProcessId")
                        .HasName("pk_worker_processes");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_worker_processes_process_id");

                    b.ToTable("worker_processes", (string)null);
                });

            modelBuilder.Entity("MesWorklog.Models.LineProcess", b =>
                {
                    b.HasOne("MesWorklog.Models.Line", null)
                        .WithMany("LineProcesses")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_processes_lines_line_id");

                    b.HasOne("MesWorklog.Models.Process", null)
                        .WithMany("LineProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_processes_processes_process_id");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLog", b =>
                {
                    b.HasOne("MesWorklog.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkLogs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_work_orders_work_order_id");

                    b.HasOne("MesWorklog.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_workers_worker_id");

                    b.Navigation("WorkOrder");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLogPause", b =>
                {
                    b.HasOne("MesWorklog.Models.PauseReason", "PauseReason")
                        .WithMany()
                        .HasForeignKey("PauseReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_log_pauses_pause_reasons_pause_reason_id");

                    b.HasOne("MesWorklog.Models.WorkLog", "WorkLog")
                        .WithMany("Pauses")
                        .HasForeignKey("WorkLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_log_pauses_work_logs_work_log_id");

                    b.Navigation("PauseReason");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkOrder", b =>
                {
                    b.HasOne("MesWorklog.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_orders_equipments_equipment_id");

                    b.HasOne("MesWorklog.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_lines_line_id");

                    b.HasOne("MesWorklog.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_processes_process_id");

                    b.Navigation("Equipment");

                    b.Navigation("Line");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkerProcess", b =>
                {
                    b.HasOne("MesWorklog.Models.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_processes_processes_process_id");

                    b.HasOne("MesWorklog.Models.Worker", null)
                        .WithMany("WorkerProcesses")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_processes_workers_worker_id");
                });

            modelBuilder.Entity("MesWorklog.Models.Line", b =>
                {
                    b.Navigation("LineProcesses");
                });

            modelBuilder.Entity("MesWorklog.Models.Process", b =>
                {
                    b.Navigation("LineProcesses");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLog", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkOrder", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("MesWorklog.Models.Worker", b =>
                {
                    b.Navigation("WorkerProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
