// <auto-generated />
using System;
using MesWorklog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesWorklog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813100350_MoveEquipmentFromWorkOrderToWorkLog")]
    partial class MoveEquipmentFromWorkOrderToWorkLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MesWorklog.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("설비 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasComment("사용여부");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("설비명");

                    b.HasKey("Id")
                        .HasName("pk_equipments");

                    b.ToTable("equipments", null, t =>
                        {
                            t.HasComment("설비");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("라인 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasComment("사용여부");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("라인명");

                    b.HasKey("Id")
                        .HasName("pk_lines");

                    b.ToTable("lines", null, t =>
                        {
                            t.HasComment("라인");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.LineProcess", b =>
                {
                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("line_id")
                        .HasComment("라인 ID");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id")
                        .HasComment("공정 ID");

                    b.HasKey("LineId", "ProcessId")
                        .HasName("pk_line_processes");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_line_processes_process_id");

                    b.ToTable("line_processes", null, t =>
                        {
                            t.HasComment("라인-공정");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.PauseReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("정지사유 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category")
                        .HasComment("분류(Planned=계획정지, Unplanned=비가동)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("정지사유명");

                    b.HasKey("Id")
                        .HasName("pk_pause_reasons");

                    b.ToTable("pause_reasons", null, t =>
                        {
                            t.HasComment("정지사유");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("공정 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasComment("사용여부");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("공정명");

                    b.HasKey("Id")
                        .HasName("pk_processes");

                    b.ToTable("processes", null, t =>
                        {
                            t.HasComment("공정");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("작업이력 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualQty")
                        .HasColumnType("int")
                        .HasColumnName("actual_qty")
                        .HasComment("실적 수량");

                    b.Property<int?>("ElapsedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("elapsed_minutes")
                        .HasComment("조업시간(분)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time")
                        .HasComment("작업 종료시각");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id")
                        .HasComment("설비 ID(수작업이면 NULL)");

                    b.Property<int?>("NetOperatingMinutes")
                        .HasColumnType("int")
                        .HasColumnName("net_operating_minutes")
                        .HasComment("실가동시간(분)");

                    b.Property<int?>("OperatingMinutes")
                        .HasColumnType("int")
                        .HasColumnName("operating_minutes")
                        .HasComment("가동시간(분)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time")
                        .HasComment("작업 시작시각");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasComment("상태(InProgress=진행중, Paused=정지중, Completed=완료)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id")
                        .HasComment("작업지시 ID");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id")
                        .HasComment("작업자 ID");

                    b.HasKey("Id")
                        .HasName("pk_work_logs");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_work_logs_equipment_id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_work_logs_start_time");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_work_logs_work_order_id");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("ix_work_logs_worker_id");

                    b.ToTable("work_logs", null, t =>
                        {
                            t.HasComment("작업이력(로그)");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLogPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("정지이력 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PauseReasonId")
                        .HasColumnType("int")
                        .HasColumnName("pause_reason_id")
                        .HasComment("정지사유 ID");

                    b.Property<DateTime>("PausedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paused_at")
                        .HasComment("정지 시각");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resumed_at")
                        .HasComment("재개 시각");

                    b.Property<int>("WorkLogId")
                        .HasColumnType("int")
                        .HasColumnName("work_log_id")
                        .HasComment("작업이력 ID");

                    b.HasKey("Id")
                        .HasName("pk_work_log_pauses");

                    b.HasIndex("PauseReasonId")
                        .HasDatabaseName("ix_work_log_pauses_pause_reason_id");

                    b.HasIndex("WorkLogId")
                        .HasDatabaseName("ix_work_log_pauses_work_log_id");

                    b.ToTable("work_log_pauses", null, t =>
                        {
                            t.HasComment("작업 정지이력");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("작업지시 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at")
                        .HasComment("완료 시각");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("line_id")
                        .HasComment("실행 라인 ID");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id")
                        .HasComment("공정 ID");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int")
                        .HasColumnName("target_qty")
                        .HasComment("목표 수량");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_work_orders_line_id");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_work_orders_process_id");

                    b.ToTable("work_orders", null, t =>
                        {
                            t.HasComment("작업지시");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("작업자 ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasComment("사용여부");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasComment("작업자명");

                    b.HasKey("Id")
                        .HasName("pk_workers");

                    b.ToTable("workers", null, t =>
                        {
                            t.HasComment("작업자");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.WorkerProcess", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int")
                        .HasColumnName("worker_id")
                        .HasComment("작업자 ID");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id")
                        .HasComment("공정 ID");

                    b.HasKey("WorkerId", "ProcessId")
                        .HasName("pk_worker_processes");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_worker_processes_process_id");

                    b.ToTable("worker_processes", null, t =>
                        {
                            t.HasComment("작업자-공정");
                        });
                });

            modelBuilder.Entity("MesWorklog.Models.LineProcess", b =>
                {
                    b.HasOne("MesWorklog.Models.Line", null)
                        .WithMany("LineProcesses")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_processes_lines_line_id");

                    b.HasOne("MesWorklog.Models.Process", null)
                        .WithMany("LineProcesses")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_processes_processes_process_id");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLog", b =>
                {
                    b.HasOne("MesWorklog.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_logs_equipments_equipment_id");

                    b.HasOne("MesWorklog.Models.WorkOrder", "WorkOrder")
                        .WithMany("WorkLogs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_work_orders_work_order_id");

                    b.HasOne("MesWorklog.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_workers_worker_id");

                    b.Navigation("Equipment");

                    b.Navigation("WorkOrder");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLogPause", b =>
                {
                    b.HasOne("MesWorklog.Models.PauseReason", "PauseReason")
                        .WithMany()
                        .HasForeignKey("PauseReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_log_pauses_pause_reasons_pause_reason_id");

                    b.HasOne("MesWorklog.Models.WorkLog", "WorkLog")
                        .WithMany("Pauses")
                        .HasForeignKey("WorkLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_log_pauses_work_logs_work_log_id");

                    b.Navigation("PauseReason");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkOrder", b =>
                {
                    b.HasOne("MesWorklog.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_lines_line_id");

                    b.HasOne("MesWorklog.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_processes_process_id");

                    b.Navigation("Line");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkerProcess", b =>
                {
                    b.HasOne("MesWorklog.Models.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_processes_processes_process_id");

                    b.HasOne("MesWorklog.Models.Worker", null)
                        .WithMany("WorkerProcesses")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_processes_workers_worker_id");
                });

            modelBuilder.Entity("MesWorklog.Models.Line", b =>
                {
                    b.Navigation("LineProcesses");
                });

            modelBuilder.Entity("MesWorklog.Models.Process", b =>
                {
                    b.Navigation("LineProcesses");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkLog", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("MesWorklog.Models.WorkOrder", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("MesWorklog.Models.Worker", b =>
                {
                    b.Navigation("WorkerProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
